name: audio_media_control
description: A new flutter plugin project.
version: 0.0.1
author: Giovanny Piovesan
homepage: github.com/wolfgio

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.wolfgio.audio_media_control
    pluginClass: AudioMediaControlPlugin